[package]
name = "max_cut_solver"
version = "0.1.0"
authors = ["xyz600 <xyz600600@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
rustc-serialize = "0.3"
plotters = "^0.3.0"
rayon = "1.5"
